### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by GeekBoxIT** [justino/p2pool-ui-punchy#10]
Is there a way I can add options to sort by Address, Hashrate, etc?

**Comment by justino** [comment]
There isn't currently, but I can put it on my roadmap for things to add

**Comment by GeekBoxIT** [comment]
@justino Any eta on that? Or how much donating could assist? I need to sort based on worker name (running a node with 100% fee) so I can easily see when a worker is down, etc.

**Comment by justino** [comment]
Ok, I created a new branch called `sortable`.
It should be able to do what you want.
Check it out and let me know if it's what you had in mind.

**Comment by justino** [comment]
@GeekBoxIT :taco:

**Comment by GeekBoxIT** [comment]
WIll check it out in the next few minutes, thanks for the prompt work. I will post follow up.

**Comment by GeekBoxIT** [comment]
Sortable branch works flawless and as needed, Thank you!
