### ISSUE TITLE
no transactions help

### ISSUE THREAD

**Issue by diaboliku** [justino/p2pool-ui-punchy#2]
I welcome your thema used in the Remote and after almost 30 share have not received any transaction , it's not like you have anything to put scam site and redirect the transaction?

**Comment by justino** [comment]
If you know how to set up p2pool, then you should know how to p2pool works. 30 shares isn't enough for anything. This UI only queries the p2pool daemon for stats, then displays the stats, it's HTML, Javascript and CSS, it's runs in your browser, not on the server. It can't intercept your miner and hijack the work.

**Comment by diaboliku** [comment]
Thx for information and ym sorry for " accused"
