### ISSUE TITLE
Hello 

### ISSUE THREAD

**Issue by diaboliku** [justino/p2pool-ui-punchy#3]
I tried to add a web interface created by you and the settings that you put in examples, but I do not go. You can help in some way to go.

http://litecoinp2pool.ddns.net:9327/static/ p2pool real address 
http://ltc.solid-service.net redirect adress

**Comment by justino** [comment]
I don't have the slightest idea what you are asking me. The first link has the UI working just fine.
The 2nd link isn't working because if the "Access-Control-Allow-Origin" header set to only allow from same origin.

**Comment by diaboliku** [comment]
Ok thx for information
