### ISSUE TITLE
Help understanding how to increase payouts

### ISSUE THREAD

**Issue by bkjwashere** [justino/p2pool-ui-punchy#5]
My payouts are 1/10th of the next miners when my hashrate is only 1/2.  How can I increase my payouts.  I don't know where to go for help on this.  I'm running 5 Baikal Giant+ miners with the +0.08 added to my address as suggested.  I don't know what else I can try

**Comment by bkjwashere** [comment]
Yesterday my payouts jumped temporarily to a reasonable place, now I'm back to 1/10th of the other miners eatimated payout & nothing changed.  Why is that & how can I keep the payments up high?

**Comment by bkjwashere** [comment]
Any insight on how to fix it would be great.  All morning, this morning, my payouts dropped 90%, with no changes that I'm aware of...the other guy in this pool is getting 40 X my payout, when he only has 4X as much GH/s.  what can I do?

**Comment by MoNTE48** [comment]
Do you understand where you are writing? This is the web ui for p2pool. It's just an interface. There are no telepaths and people who can help you.

**Comment by justino** [comment]
Closed, off topic
