### ISSUE TITLE
Link to bchain invalid

### ISSUE THREAD

**Issue by holmes6** [justino/p2pool-ui-punchy#8]
currently https://bchain.info/VTC/address/[VTC_ADDRESS] returns a generic page
desired page is found at: https://bchain.info/VTC/addr/[VTC_ADDRESS]

**Comment by justino** [comment]
This UI doesn't specify what the URL should be. Instead, it queries the p2pool server that it's a UI for, and it receives the link. The problem is in the p2pool node, not this UI.
